# Usa una imagen base para Python
FROM python:3.10-slim

# Configura el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto
COPY . .

# Instala dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto para la app
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "src/app.py"]
